version: "3.3"

services:
  db:
    container_name: sql-for-scientists
    build: .
    env_file:
      - creds.env
    ports:
      - 33060:3306
    cap_add:
      - SYS_NICE  # avoids `mbind: Operation not permitted`
